buildVariable: false
familyName: Noto Sans Inscriptional Parthian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSansInscriptionalParthian.glyphs
